<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>

		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Calendar</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css" />
        <link rel="stylesheet" href="css/style.css">
		<?
		$this->include_css_files();
		$this->include_js_files();
		?>
	</head>

	<body>
    <?= $this->print_view(); ?>

<!--    jQuery UI datepicker-->
<!--<div class="col-lg-12 date-search">-->
<!--    <div class="input-group">-->
<!--        <input type="submit" id="datepicker" class="form-control" placeholder="Pick a date">-->
<!--      <span class="input-group-btn">-->
<!--        <button class="btn btn-primary" type="button">Go!</button>-->
<!--      </span>-->
<!--    </div>-->
<!--</div>-->
-<!--end datepicker-->


<!--        begin modal for note input-->
        <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <form method="POST" class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel"></h4>
                    </div >
                    <div class="modal-body">
                        <input  type="hidden" name="date" id="input-date" >
                        <input id="title" type="text" class="form-control" name="title" placeholder="Note Title">
                        </br>
                        <textarea id="body" class="form-control" rows="3" name="body"></textarea>
                    </div>
                    <div class="modal-footer">
<!--                        <button type="button" class="btn btn-danger" data-dismiss="modal">Delete</button>-->
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button id="form-submit" type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
                    </div>
                    <div class="note-view"></div>

                </form>

            </div>
        </div>
<!--    end modal-->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="js/jQuery.js"></script>
	</body>
</html>
